/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BadgesRouteImport } from './routes/badges'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as GuildHallRouteImport } from './routes/guild-hall'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SecretBaseRouteImport } from './routes/secret-base'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesSlugRouteImport } from './routes/courses/$slug'
import { Route as JournalIndexRouteImport } from './routes/journal.index'
import { Route as JournalSlugRouteImport } from './routes/journal/$slug'
import { Route as CoursesSlugMasteryRouteImport } from './routes/courses/$slug_.mastery'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BadgesRoute = BadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const GuildHallRoute = GuildHallRouteImport.update({
  id: '/guild-hall',
  path: '/guild-hall',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretBaseRoute = SecretBaseRouteImport.update({
  id: '/secret-base',
  path: '/secret-base',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesRoute,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CoursesRoute,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JournalRoute,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => JournalRoute,
} as any)
const CoursesSlugMasteryRoute = CoursesSlugMasteryRouteImport.update({
  id: '/$slug_/mastery',
  path: '/$slug/mastery',
  getParentRoute: () => CoursesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/badges': typeof BadgesRoute
  '/courses': typeof CoursesRouteWithChildren
  '/guild-hall': typeof GuildHallRoute
  '/journal': typeof JournalRouteWithChildren
  '/journey': typeof JourneyRoute
  '/search': typeof SearchRoute
  '/secret-base': typeof SecretBaseRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/courses/': typeof CoursesIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/courses/$slug/mastery': typeof CoursesSlugMasteryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/badges': typeof BadgesRoute
  '/guild-hall': typeof GuildHallRoute
  '/journey': typeof JourneyRoute
  '/search': typeof SearchRoute
  '/secret-base': typeof SecretBaseRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/courses': typeof CoursesIndexRoute
  '/journal': typeof JournalIndexRoute
  '/courses/$slug/mastery': typeof CoursesSlugMasteryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/badges': typeof BadgesRoute
  '/courses': typeof CoursesRouteWithChildren
  '/guild-hall': typeof GuildHallRoute
  '/journal': typeof JournalRouteWithChildren
  '/journey': typeof JourneyRoute
  '/search': typeof SearchRoute
  '/secret-base': typeof SecretBaseRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/courses/': typeof CoursesIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/courses/$slug_/mastery': typeof CoursesSlugMasteryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/badges'
    | '/courses'
    | '/guild-hall'
    | '/journal'
    | '/journey'
    | '/search'
    | '/secret-base'
    | '/courses/$slug'
    | '/journal/$slug'
    | '/courses/'
    | '/journal/'
    | '/courses/$slug/mastery'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/badges'
    | '/guild-hall'
    | '/journey'
    | '/search'
    | '/secret-base'
    | '/courses/$slug'
    | '/journal/$slug'
    | '/courses'
    | '/journal'
    | '/courses/$slug/mastery'
  id:
    | '__root__'
    | '/'
    | '/badges'
    | '/courses'
    | '/guild-hall'
    | '/journal'
    | '/journey'
    | '/search'
    | '/secret-base'
    | '/courses/$slug'
    | '/journal/$slug'
    | '/courses/'
    | '/journal/'
    | '/courses/$slug_/mastery'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BadgesRoute: typeof BadgesRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  GuildHallRoute: typeof GuildHallRoute
  JournalRoute: typeof JournalRouteWithChildren
  JourneyRoute: typeof JourneyRoute
  SearchRoute: typeof SearchRoute
  SecretBaseRoute: typeof SecretBaseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badges': {
      id: '/badges'
      path: '/badges'
      fullPath: '/badges'
      preLoaderRoute: typeof BadgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guild-hall': {
      id: '/guild-hall'
      path: '/guild-hall'
      fullPath: '/guild-hall'
      preLoaderRoute: typeof GuildHallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secret-base': {
      id: '/secret-base'
      path: '/secret-base'
      fullPath: '/secret-base'
      preLoaderRoute: typeof SecretBaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/journal/': {
      id: '/journal/'
      path: '/'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof JournalRoute
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof JournalRoute
    }
    '/courses/$slug_/mastery': {
      id: '/courses/$slug_/mastery'
      path: '/$slug/mastery'
      fullPath: '/courses/$slug/mastery'
      preLoaderRoute: typeof CoursesSlugMasteryRouteImport
      parentRoute: typeof CoursesRoute
    }
  }
}

interface CoursesRouteChildren {
  CoursesSlugRoute: typeof CoursesSlugRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  CoursesSlugMasteryRoute: typeof CoursesSlugMasteryRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesSlugRoute: CoursesSlugRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  CoursesSlugMasteryRoute: CoursesSlugMasteryRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

interface JournalRouteChildren {
  JournalSlugRoute: typeof JournalSlugRoute
  JournalIndexRoute: typeof JournalIndexRoute
}

const JournalRouteChildren: JournalRouteChildren = {
  JournalSlugRoute: JournalSlugRoute,
  JournalIndexRoute: JournalIndexRoute,
}

const JournalRouteWithChildren =
  JournalRoute._addFileChildren(JournalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BadgesRoute: BadgesRoute,
  CoursesRoute: CoursesRouteWithChildren,
  GuildHallRoute: GuildHallRoute,
  JournalRoute: JournalRouteWithChildren,
  JourneyRoute: JourneyRoute,
  SearchRoute: SearchRoute,
  SecretBaseRoute: SecretBaseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
